/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Saaty.Criteria;


import Data.Structurs;
import java.awt.FlowLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JTextField;


public class PanelSaatyMatriz extends javax.swing.JPanel {

    public PanelSaatyMatriz() {
        initComponents();
        addJList();
        events =new saatyGuiEvents();
        this.setBounds(150, 0, 902, 448);
        elements=new ArrayList();
        contador=0;
        Structurs.eigenvector=new ArrayList();
        sliders=new ArrayList<JSlider>();
        consistence=new Consistence();
        txtElementOnlyLetters(txtElement);
    }
    
    private void addJList(){
        listModel = new DefaultListModel();
        listElements = new JList(listModel);  
        JScrollPane scrollPane = new JScrollPane(listElements);
        listElements.setBounds(55, 150, 200, 150);
        internalPanelSaatyElements.add(listElements);
        jPanel1.setLayout(new FlowLayout(FlowLayout.CENTER));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalPanelSaatyElements = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddElement = new javax.swing.JButton();
        txtElement = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(902, 448));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(902, 488));

        internalPanelSaatyElements.setBackground(new java.awt.Color(254, 254, 254));
        internalPanelSaatyElements.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nuevo criterio:");

        btnAddElement.setBackground(new java.awt.Color(254, 254, 254));
        btnAddElement.setText("Agregar Criterio");
        btnAddElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddElementActionPerformed(evt);
            }
        });

        txtElement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtElementKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtElementKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtElementKeyTyped(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(254, 254, 254));
        btnRemove.setText("Eliminar Criterio");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internalPanelSaatyElementsLayout = new javax.swing.GroupLayout(internalPanelSaatyElements);
        internalPanelSaatyElements.setLayout(internalPanelSaatyElementsLayout);
        internalPanelSaatyElementsLayout.setHorizontalGroup(
            internalPanelSaatyElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalPanelSaatyElementsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(internalPanelSaatyElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(internalPanelSaatyElementsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtElement, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(internalPanelSaatyElementsLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(internalPanelSaatyElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove)
                            .addComponent(btnAddElement))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        internalPanelSaatyElementsLayout.setVerticalGroup(
            internalPanelSaatyElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalPanelSaatyElementsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(internalPanelSaatyElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnAddElement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(btnRemove)
                .addGap(34, 34, 34))
        );

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Asignar Valores"));
        jPanel1.setMaximumSize(new java.awt.Dimension(669, 414));
        jPanel1.setMinimumSize(new java.awt.Dimension(669, 414));
        jPanel1.setPreferredSize(new java.awt.Dimension(669, 414));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internalPanelSaatyElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(internalPanelSaatyElements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddElementActionPerformed
        events.addNewElement(txtElement, listModel, listElements, elements, jPanel1);
    }//GEN-LAST:event_btnAddElementActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        events.removeListElement(listModel, listElements, elements, jPanel1);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtElementKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtElementKeyTyped
       
    }//GEN-LAST:event_txtElementKeyTyped

    private void txtElementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtElementKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElementKeyReleased

    private void txtElementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtElementKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            events.addNewElement(txtElement, listModel, listElements, elements, jPanel1);
        }       
    }//GEN-LAST:event_txtElementKeyPressed
    
    public void txtElementOnlyLetters(JTextField a)
    {
        a.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent e)
            {
                char c = e.getKeyChar();
                if(Character.isLetter(c))
                {
                    e.setKeyChar(Character.toUpperCase(c));
                }
                else
                {   
                    e.consume();
                }
            }
        });
    }
    Matrix matrix;
    Consistence consistence;
    public DefaultListModel listModel;
    public static ArrayList<JSlider> sliders;
    public static ArrayList elements;
    private JList listElements;
    saatyGuiEvents events; 
    int contador;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddElement;
    private javax.swing.JButton btnRemove;
    private javax.swing.JPanel internalPanelSaatyElements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtElement;
    // End of variables declaration//GEN-END:variables
}
