/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SaatyDecisors.GUI;


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;


public class PanelSaatyDecisorsMatriz extends javax.swing.JPanel {

    public PanelSaatyDecisorsMatriz(int panelNo) {
        initComponents();
        events =new DecisorsSaatyGuiEvents();
        consistence=new DecisorsConsistence();
        elements=new ArrayList();
        contador=0;
        events.addNewVersionJSlidersElement(this.jPanel1, panelNo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(902, 580));
        setMinimumSize(new java.awt.Dimension(902, 580));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(902, 580));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Asignar valores"));
        jPanel1.setMaximumSize(new java.awt.Dimension(537, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(537, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(537, 450));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public DefaultListModel listModel;
    private DecisorsMatrix matrix;
    DecisorsConsistence consistence;
    public JList listElements;
    DecisorsSaatyGuiEvents events; 
    public ArrayList elements;
    int contador;
    public int cantDecisors=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
